#!/usr/bin/python3

def raise_exception():
    list_a = [1, 2, 3]
    print("{:d}".format(list_a))
